### ISSUE TITLE
Allow _ember-perf-timeline queryParam to be configurable

### ISSUE THREAD

**Issue by rondale-sc** [ember-best-practices/ember-perf-timeline#19]
On my project I have a lot of custom performance benchmarking in the fashion of ember-observer.  And I'd like to see these (ember-perf-timeline) benchmarks when using my own custom queryParam (in this case `perf.profile` and a few other `perf` queryParams) for my app's benchmarking.

Is this a silly thing, or worthwhile (before I work on anything)

**Comment by stefanpenner** [comment]
> Is this a silly thing, or worthwhile (before I work on anything)

sounds reasonable to me
